<?php

namespace Eesn2\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Bajas_DocentesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bajas_DocentesRepository extends EntityRepository
{
}
