<?php

namespace Eesn2\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Descripcion_CargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Descripcion_CargoRepository extends EntityRepository
{
}
