<?php

namespace Eesn2\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Sit_RevistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sit_RevistaRepository extends EntityRepository
{
}
