<?php

namespace Eesn2\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Solicitudes_ExamenesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Solicitudes_ExamenesRepository extends EntityRepository
{
}
