<?php

namespace Eesn2\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Tercer_TrimestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tercer_TrimestreRepository extends EntityRepository
{
}
